import type { Notification } from "@/types/notification";

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    type: "TRANSAKSI",
    title: "Transaksi dikonfirmasi",
    message: "Transaksi PGL-202605-012 sebesar Rp 450.000 telah dikonfirmasi oleh Sari Dewi",
    isRead: false,
    createdAt: "2026-05-25T10:30:00Z",
    relatedUrl: "/transaksi",
  },
  {
    id: "n2",
    type: "PETTY_CASH",
    title: "Petty cash hampir habis",
    message: "Saldo petty cash Kantor Pusat Jakarta tersisa Rp 1.800.000 dari limit Rp 5.000.000 (36%)",
    isRead: false,
    createdAt: "2026-05-25T09:15:00Z",
    relatedUrl: "/petty-cash",
  },
  {
    id: "n3",
    type: "SALDO",
    title: "Saldo kantor rendah",
    message: "Saldo Kantor Cabang Bandung di bawah threshold Rp 5.000.000. Saldo saat ini: Rp 3.250.000",
    isRead: false,
    createdAt: "2026-05-24T16:00:00Z",
    relatedUrl: "/kantor",
  },
  {
    id: "n4",
    type: "TRANSAKSI",
    title: "Transaksi baru",
    message: "Andi Kurniawan mencatat pengeluaran Grab ke klien sebesar Rp 125.000",
    isRead: true,
    createdAt: "2026-05-24T09:30:00Z",
    relatedUrl: "/transaksi",
  },
  {
    id: "n5",
    type: "TRANSAKSI",
    title: "Transaksi baru",
    message: "Rina Sari mencatat pemasukan servis maintenance server sebesar Rp 3.500.000",
    isRead: true,
    createdAt: "2026-05-23T14:00:00Z",
    relatedUrl: "/transaksi",
  },
  {
    id: "n6",
    type: "PETTY_CASH",
    title: "Top up petty cash",
    message: "Petty cash Kantor Pusat Jakarta telah di-top up sebesar Rp 2.000.000 oleh Admin",
    isRead: true,
    createdAt: "2026-05-22T11:00:00Z",
    relatedUrl: "/petty-cash",
  },
  {
    id: "n7",
    type: "SYSTEM",
    title: "Kantor baru ditambahkan",
    message: "Cabang Bali telah ditambahkan ke dalam sistem oleh Admin",
    isRead: true,
    createdAt: "2026-05-20T08:00:00Z",
    relatedUrl: "/kantor",
  },
  {
    id: "n8",
    type: "TRANSAKSI",
    title: "Transaksi ditolak",
    message: "Transaksi PGL-202605-006 ditolak oleh Admin. Alasan: Bukti tidak lengkap",
    isRead: true,
    createdAt: "2026-05-19T15:30:00Z",
    relatedUrl: "/transaksi",
  },
];
